'use client'
import {useEffect,useState} from 'react'
const roles=['Super Admin','IMS Admin','Auditor','Function Owner','Viewer']
export default function Admin(){
 const [tab,setTab]=useState('workflow'),[flows,setFlows]=useState([]),[users,setUsers]=useState([]),[audit,setAudit]=useState([]),[msg,setMsg]=useState(''),[wf,setWf]=useState({module:'Document & Record Control',name:'Document Approval',description:''}),[level,setLevel]=useState({workflow_id:'',level_no:1,level_name:'Review',description:'',required_role:'Function Owner',required_approvals:1})
 const get=async(url,setter)=>{const r=await fetch(url);if(r.ok)setter(await r.json())}
 const load=()=>{get('/api/workflows',setFlows);get('/api/users',setUsers);get('/api/audit',setAudit)}
 useEffect(load,[])
 const createWorkflow=async e=>{e.preventDefault();setMsg('');const r=await fetch('/api/workflows',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(wf)});setMsg(r.ok?'Workflow created':'Unable to create workflow');if(r.ok){setWf({...wf,name:'',description:''});load()}}
 const addLevel=async e=>{e.preventDefault();setMsg('');const r=await fetch('/api/workflows/levels',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(level)});setMsg(r.ok?'Approval level added':'Unable to add approval level');if(r.ok)load()}
 const removeLevel=async id=>{if(!confirm('Remove this approval level?'))return;const r=await fetch('/api/workflows/levels?id='+id,{method:'DELETE'});setMsg(r.ok?'Approval level removed':'Unable to remove level');if(r.ok)load()}
 const updateUser=async(u,patch)=>{const body={id:u.id,app_role:patch.app_role??u.app_role,active:patch.active??u.active};const r=await fetch('/api/users',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setMsg(r.ok?'Access updated':'Access update rejected');if(r.ok)load()}
 return <main style={{padding:32,maxWidth:1250,margin:'auto'}}><a href="/">← Control Room</a><h1>IMS Administration Center</h1><p>Access control, configurable multi-level approval and governance traceability.</p><nav style={{display:'flex',gap:8,margin:'24px 0'}}>{['workflow','users','audit'].map(x=><button key={x} className={tab===x?'primary':''} onClick={()=>setTab(x)}>{x.toUpperCase()}</button>)}</nav>{msg&&<p className="pill">{msg}</p>}
 {tab==='workflow'&&<section><h2>Approval Flow Designer</h2><div className="grid"><form className="panel" onSubmit={createWorkflow}><h3>New Workflow</h3><label>Module<input value={wf.module} onChange={e=>setWf({...wf,module:e.target.value})}/></label><label>Name<input required value={wf.name} onChange={e=>setWf({...wf,name:e.target.value})}/></label><label>Keterangan<textarea rows="3" value={wf.description} onChange={e=>setWf({...wf,description:e.target.value})}/></label><button className="primary">Create Workflow</button></form><form className="panel" onSubmit={addLevel}><h3>Add Approval Level</h3><label>Workflow<select required value={level.workflow_id} onChange={e=>setLevel({...level,workflow_id:e.target.value})}><option value="">Select workflow</option>{flows.map(w=><option value={w.id} key={w.id}>{w.module} · {w.name}</option>)}</select></label><div className="formgrid"><label>Level<input type="number" min="1" value={level.level_no} onChange={e=>setLevel({...level,level_no:Number(e.target.value)})}/></label><label>Approvals<input type="number" min="1" value={level.required_approvals} onChange={e=>setLevel({...level,required_approvals:Number(e.target.value)})}/></label></div><label>Level name<input required value={level.level_name} onChange={e=>setLevel({...level,level_name:e.target.value})}/></label><label>Required role<select value={level.required_role} onChange={e=>setLevel({...level,required_role:e.target.value})}>{roles.map(r=><option key={r}>{r}</option>)}</select></label><label>Keterangan<textarea rows="3" value={level.description} onChange={e=>setLevel({...level,description:e.target.value})}/></label><button className="primary">Add Level</button></form></div>{flows.map(w=><article className="panel" key={w.id}><div className="panelhead"><div><b>{w.module} · {w.name}</b><p>{w.description||'No description'}</p></div><span className="pill">{w.active?'Active':'Inactive'}</span></div><ol>{w.levels.map(l=><li key={l.id} style={{margin:'10px 0'}}><b>L{l.level_no} · {l.level_name}</b> — {l.required_role} ({l.required_approvals} approval) {l.description&&<small> · {l.description}</small>} <button type="button" onClick={()=>removeLevel(l.id)}>Remove</button></li>)}</ol></article>)}</section>}
 {tab==='users'&&<section><h2>User & Access Management</h2><table><thead><tr><th>Name</th><th>Email</th><th>Function</th><th>Role</th><th>Active</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.full_name}</td><td>{u.email}</td><td>{u.function_name||'-'}</td><td><select value={u.app_role} onChange={e=>updateUser(u,{app_role:e.target.value})}>{roles.map(r=><option key={r}>{r}</option>)}</select></td><td><input type="checkbox" checked={u.active} onChange={e=>updateUser(u,{active:e.target.checked})}/></td></tr>)}</tbody></table></section>}
 {tab==='audit'&&<section><h2>Audit Trail</h2>{audit.map(a=><article className="panel" key={a.id}><b>{a.action}</b> · {a.entity_type} · {a.actor||'System'}<br/><small>{new Date(a.created_at).toLocaleString()}</small></article>)}</section>}</main>
}
