'use client'
import {useMemo,useState} from 'react'

export default function ModuleWorkspace({module,records=[],onOpen,onNew}){
 const[query,setQuery]=useState(''),[status,setStatus]=useState('Semua'),[severity,setSeverity]=useState('Semua')
 const all=useMemo(()=>records.filter(r=>r.module===module),[records,module])
 const items=useMemo(()=>all.filter(r=>status==='Semua'||r.status===status).filter(r=>severity==='Semua'||r.severity===severity).filter(r=>!query||`${r.record_no||''} ${r.title||''} ${r.owner||''} ${r.description||''}`.toLowerCase().includes(query.toLowerCase())),[all,query,status,severity])
 const open=all.filter(r=>!['Approved','Closed'].includes(r.status)).length,critical=all.filter(r=>['Major','Critical'].includes(r.severity)&&!['Approved','Closed'].includes(r.status)).length,overdue=all.filter(r=>r.due_date&&!['Approved','Closed'].includes(r.status)&&new Date(r.due_date)<new Date(new Date().toDateString())).length,closed=all.length-open,completion=all.length?Math.round(closed/all.length*100):100
 const quick=(nextStatus,nextSeverity)=>{setStatus(nextStatus);setSeverity(nextSeverity);setQuery('')}
 return <section className="docworkspace"><div className="dochead"><div><p className="eyebrow">OPERATIONAL WORKSPACE</p><h2>{module}</h2><p>Register operasional, tindak lanjut, dan bukti pemenuhan IMS.</p></div><div className="docactions"><button className="primary" onClick={onNew}>＋ New Record</button></div></div><div className="metrics modulemetrics"><button type="button" onClick={()=>quick('Semua','Semua')}><b>{all.length}</b><span>Total Record</span></button><button type="button" onClick={()=>quick('Open','Semua')}><b>{open}</b><span>Perlu Tindak Lanjut</span></button><button type="button" onClick={()=>quick('Semua','Major')}><b>{critical}</b><span>Major / Critical</span></button><button type="button" onClick={()=>quick('Semua','Semua')}><b>{overdue}</b><span>Overdue</span></button></div><div className="modulehealth"><div><span>Completion / Closed</span><b>{completion}%</b></div><div className="progressstack"><i style={{width:completion+'%'}}></i></div><small>{closed} selesai dari {all.length} record · {open} masih aktif · {overdue} melewati due date</small></div><div className="docfilters"><select value={status} onChange={e=>setStatus(e.target.value)}><option>Semua</option>{['Open','In Review','Approved','Closed'].map(x=><option key={x}>{x}</option>)}</select><select value={severity} onChange={e=>setSeverity(e.target.value)}><option>Semua</option>{['Low','Medium','Major','Critical'].map(x=><option key={x}>{x}</option>)}</select><input placeholder="Cari nomor, judul, PIC, keterangan..." value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={()=>quick('Semua','Semua')}>Reset</button></div>{items.length?<table><thead><tr><th>No.</th><th>Record</th><th>Judul</th><th>Status</th><th>Severity</th><th>Due Date</th><th>PIC</th><th>Aksi</th></tr></thead><tbody>{items.map((r,i)=><tr key={r.id}><td>{i+1}</td><td><button className="linkbtn" onClick={()=>onOpen(r)}>{r.record_no}</button></td><td>{r.title}</td><td><span className={'status '+String(r.status||'').toLowerCase().replaceAll(' ','-')}>{r.status}</span></td><td>{r.severity||'-'}</td><td>{r.due_date||'-'}</td><td>{r.owner||'Unassigned'}</td><td><button className="more" onClick={()=>onOpen(r)} title="Buka detail, approval, lampiran dan audit trail">•••</button></td></tr>)}</tbody></table>:<div className="empty">Belum ada record yang sesuai filter pada modul ini.</div>}</section>
}
