'use client'
import {useMemo,useState} from 'react'

export default function ModuleWorkspace({module,records=[],onOpen,onNew}){
 const[query,setQuery]=useState(''),[status,setStatus]=useState('Semua'),[severity,setSeverity]=useState('Semua')
 const items=useMemo(()=>records.filter(r=>r.module===module).filter(r=>status==='Semua'||r.status===status).filter(r=>severity==='Semua'||r.severity===severity).filter(r=>!query||`${r.record_no||''} ${r.title||''} ${r.owner||''} ${r.description||''}`.toLowerCase().includes(query.toLowerCase())),[records,module,query,status,severity])
 const all=records.filter(r=>r.module===module),open=all.filter(r=>!['Approved','Closed'].includes(r.status)).length,critical=all.filter(r=>['Major','Critical'].includes(r.severity)&&!['Approved','Closed'].includes(r.status)).length,overdue=all.filter(r=>r.due_date&&!['Approved','Closed'].includes(r.status)&&new Date(r.due_date)<new Date(new Date().toDateString())).length
 return <section className="docworkspace"><div className="dochead"><div><h2>{module}</h2><p>Register operasional, tindak lanjut, dan bukti pemenuhan IMS.</p></div><div className="docactions"><button className="primary" onClick={onNew}>＋ New Record</button></div></div><div className="metrics modulemetrics"><div><b>{all.length}</b><span>Total Record</span></div><div><b>{open}</b><span>Perlu Tindak Lanjut</span></div><div><b>{critical}</b><span>Major / Critical</span></div><div><b>{overdue}</b><span>Overdue</span></div></div><div className="docfilters"><select value={status} onChange={e=>setStatus(e.target.value)}><option>Semua</option>{['Open','In Review','Approved','Closed'].map(x=><option key={x}>{x}</option>)}</select><select value={severity} onChange={e=>setSeverity(e.target.value)}><option>Semua</option>{['Low','Medium','Major','Critical'].map(x=><option key={x}>{x}</option>)}</select><input placeholder="Cari nomor, judul, PIC, keterangan..." value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={()=>{setQuery('');setStatus('Semua');setSeverity('Semua')}}>Reset</button></div>{items.length?<table><thead><tr><th>No.</th><th>Record</th><th>Judul</th><th>Status</th><th>Severity</th><th>Due Date</th><th>PIC</th><th>Aksi</th></tr></thead><tbody>{items.map((r,i)=><tr key={r.id}><td>{i+1}</td><td><button className="linkbtn" onClick={()=>onOpen(r)}>{r.record_no}</button></td><td>{r.title}</td><td><span className={'status '+String(r.status||'').toLowerCase().replaceAll(' ','-')}>{r.status}</span></td><td>{r.severity||'-'}</td><td>{r.due_date||'-'}</td><td>{r.owner||'Unassigned'}</td><td><button className="more" onClick={()=>onOpen(r)} title="Buka detail, approval, lampiran, distribusi dan audit trail">•••</button></td></tr>)}</tbody></table>:<div className="empty">Belum ada record yang sesuai filter pada modul ini.</div>}</section>
}
