'use client'
import {useMemo,useState} from 'react'

const RISK_MATRIX={1:{1:'N',2:'L',3:'L',4:'M',5:'H'},2:{1:'L',2:'L',3:'M',4:'M',5:'H'},3:{1:'L',2:'L',3:'M',4:'H',5:'H'},4:{1:'L',2:'M',3:'H',4:'H',5:'E'},5:{1:'M',2:'M',3:'H',4:'E',5:'E'}}
const level=(p,s)=>RISK_MATRIX[Number(p)]?.[Number(s)]||''
const LIKELIHOOD={1:'Tidak mungkin · 1–20% · <1 kali/5 tahun',2:'Mungkin · 21–40% · 1 kali/5 tahun',3:'Kemungkinan Besar · 41–60% · 1 kali/tahun–5 tahun',4:'Hampir Pasti · 61–80% · 1 kali/kuartal–tahun',5:'Pasti · 81–99% · 1 kali/bulan–kuartal'}
const LEVEL_NAME={N:'Negligible',L:'Low',M:'Medium',H:'High',E:'Extreme'}
const OPPORTUNITY_GUIDE={Keuangan:['Dapat diabaikan / <5% perbedaan anggaran','Mencapai target profit/departemen / <10% anggaran','Profit/target >10% / <20% anggaran','Profit/target >20% / <30% anggaran','Profit/target >30% / <40% anggaran'],Kesehatan:['Efek positif dapat diabaikan','Efek positif tanpa perubahan kualitas hidup','Efek positif permanen signifikan pada kualitas hidup','Kasus 10 penyakit terbesar turun 50%','Tidak ada kasus 10 penyakit terbesar / penghargaan kesehatan'],Keselamatan:['Dapat diabaikan','Tidak ada LTI/fatality 1 bulan','Tidak ada LTI/fatality 6 bulan','Tidak ada LTI/fatality/near miss 1 tahun','Tidak ada LTI/fatality/near miss >5 tahun'],'Lingkungan Hidup':['Dampak positif dapat diabaikan','Dampak positif kecil dalam konsesi','Dampak positif besar dalam konsesi','Perbaikan lingkungan luas <5 km','Perbaikan lingkungan luas 5–10 km'],'Hukum & Kepatuhan':['Dapat diabaikan','Patuh 100% terhadap peraturan','Beyond compliance sedikit di atas persyaratan','Beyond compliance + penghargaan lokal/nasional','Beyond compliance + penghargaan nasional/internasional'],Reputasi:['Dampak positif dapat diabaikan','Respons positif masyarakat sekitar','Respons positif pemerintah lokal','Liputan positif/penghargaan nasional','Liputan positif nasional/internasional + penghargaan internasional'],Hubungan:['Dampak positif dapat diabaikan','Hubungan positif skala kecil','Hubungan positif masyarakat/pemerintah/pelanggan','Hubungan sangat baik + manfaat/peluang baru','Hubungan luar biasa + award/kontrak/pelanggan baru'],'Sumber Daya Manusia':['Dampak positif dapat diabaikan','Dampak positif kecil pada beberapa karyawan','Dampak positif menengah pada sebagian besar karyawan','Dampak besar + peluang promosi staf/manajemen junior','Dampak luar biasa + promosi manajemen'],Waktu:['Lebih cepat ≤10% dari rencana','Lebih cepat >10–15%','Lebih cepat >15–20%','Lebih cepat >20–25%','Lebih cepat >25–30%'],Kualitas:['Dampak positif dapat diabaikan','Peningkatan kecil','Peningkatan besar','Peningkatan sangat signifikan','Peningkatan exceptional/luar biasa'],'Aset Fisik':['Keuntungan kecil pada proses inti fungsi','Keuntungan besar pada proses inti fungsi','Keuntungan kecil di luar fungsi','Keuntungan besar di luar fungsi','Keuntungan signifikan tingkat aset']}
const guideFor=(kind,area)=>kind==='Opportunity'?(OPPORTUNITY_GUIDE[area]||IMPACT_GUIDE[area]):IMPACT_GUIDE[area]
const IMPACT_AREAS=['Keuangan','Kesehatan','Keselamatan','Lingkungan Hidup','Hukum & Kepatuhan','Reputasi','Hubungan','Sumber Daya Manusia','Waktu','Kualitas','Aset Fisik']
const IMPACT_GUIDE={Keuangan:['≤ USD 1M / dampak anggaran terendah','> USD 1M–6M','> USD 6M–10M','> USD 10M–20M','> USD 20M'],Keselamatan:['Pertolongan Pertama','Pengobatan Medis','RWDI / Minor LTI <20 hari','Major LTI / kematian atau cacat tunggal','Beberapa korban jiwa / cacat'],Waktu:['≤10% deviasi waktu','>10–15%','>15–20%','>20–25%','>25–30%'],Kualitas:['Dampak dapat diabaikan dalam fungsi','Dampak kecil di luar fungsi','Dampak besar pada proses berikutnya','Dampak parah pada bagian besar organisasi','Dampak menyeluruh organisasi'], 'Aset Fisik':['Dampak kecil pada proses inti fungsi','Dampak besar pada proses inti fungsi','Dampak kecil di luar fungsi','Dampak besar di luar fungsi','Dampak signifikan tingkat aset'],Reputasi:['Dapat diabaikan','<1 hari, tanpa liputan berita','≥1 hari, tanpa liputan berita','Liputan media lokal','Liputan media daerah/nasional'],Hubungan:['Dampak dapat diabaikan','Hubungan pihak kecil sedikit terpengaruh','Hubungan masyarakat/pemerintah terpengaruh','Hubungan lokal rusak serius','Hubungan regional rusak serius'], 'Sumber Daya Manusia':['Dapat diabaikan','Dampak kecil pada beberapa karyawan','Dampak besar pada sebagian besar karyawan','Dampak serius / turnover staf-manajemen junior','Dampak sangat serius / turnover manajemen'],Kesehatan:['Paparan kemungkinan tidak menyebabkan bahaya','Efek kesehatan tanpa ancaman kualitas hidup','Efek permanen tanpa pengaruh signifikan kualitas hidup','Efek permanen menurunkan kualitas/panjang umur','Cacat fisik/mental permanen atau penyakit jangka panjang'],'Lingkungan Hidup':['Dampak dapat diabaikan','Dampak kecil dalam konsesi','Kerusakan besar dalam konsesi','Kerusakan lokal <5 km','Kerusakan luas 5–10 km'],'Hukum & Kepatuhan':['Dampak/sanksi dapat diabaikan','Sanksi administratif/keuangan rendah','Peringatan/teguran regulator','Lisensi kecil terancam/ditangguhkan','Lisensi besar/sanksi pidana serius']}
const empty={context_type:'Internal',swot_type:'Strength',issue:'',initial_probability:'',initial_severity:'',risk_or_opportunity:'Risk',impact_area:'',action_plan:'',department:'',residual_probability:'',residual_severity:'',opportunity_effectiveness:'Dalam Progres',further_action_plan:'',owner_id:''}

export default function RiskOpportunityWorkspace({records=[],users=[],canWrite=false,onRefresh,onOpen}){
 const [form,setForm]=useState(empty),[show,setShow]=useState(false),[saving,setSaving]=useState(false),[notice,setNotice]=useState(''),[kindFilter,setKindFilter]=useState('Semua'),[swotFilter,setSwotFilter]=useState('Semua')
 const allItems=useMemo(()=>records.filter(r=>r.module==='Risk & Opportunity'),[records]),items=useMemo(()=>allItems.filter(r=>kindFilter==='Semua'||r.risk_or_opportunity===kindFilter).filter(r=>swotFilter==='Semua'||r.swot_type===swotFilter),[allItems,kindFilter,swotFilter]),kpi=useMemo(()=>({total:allItems.length,risk:allItems.filter(r=>r.risk_or_opportunity==='Risk').length,opportunity:allItems.filter(r=>r.risk_or_opportunity==='Opportunity').length,high:allItems.filter(r=>['H','E'].includes(level(r.initial_probability,r.initial_severity))).length,residualHigh:allItems.filter(r=>['H','E'].includes(level(r.residual_probability,r.residual_severity))).length,improved:allItems.filter(r=>r.residual_score!=null&&r.initial_score!=null&&Number(r.residual_score)<Number(r.initial_score)).length}),[allItems])
 const submit=async e=>{e.preventDefault();if(!canWrite)return;setSaving(true);setNotice('');const payload={title:form.issue,module:'Risk & Opportunity',severity:level(form.initial_probability,form.initial_severity)||'Medium',description:form.action_plan,owner_id:form.owner_id||null,risk:{...form,initial_probability:Number(form.initial_probability),initial_severity:Number(form.initial_severity),residual_probability:form.residual_probability?Number(form.residual_probability):null,residual_severity:form.residual_severity?Number(form.residual_severity):null}};const r=await fetch('/api/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),d=await r.json().catch(()=>({}));if(!r.ok){setNotice(d.error||'Gagal menyimpan Risk & Opportunity');setSaving(false);return}setForm(empty);setShow(false);setSaving(false);setNotice('Risk & Opportunity berhasil ditambahkan.');if(onRefresh)await onRefresh()}
 return <section className="docworkspace"><div className="dochead"><div><h2>Risk & Opportunity — SWOT</h2><p>Format diselaraskan dengan register SWOT IMM: konteks organisasi, initial risk/opportunity, action plan, residual risk, efektivitas peluang, dan further action.</p></div>{canWrite&&<button className="primary" onClick={()=>setShow(!show)}>＋ Risk / Opportunity</button>}</div>
 {notice&&<div className="notice"><span>{notice}</span></div>}<div className="metrics modulemetrics"><button type="button" onClick={()=>setKindFilter('Semua')}><b>{kpi.total}</b><span>Total</span></button><button type="button" onClick={()=>setKindFilter('Risk')}><b>{kpi.risk}</b><span>Risk</span></button><button type="button" onClick={()=>setKindFilter('Opportunity')}><b>{kpi.opportunity}</b><span>Opportunity</span></button><button type="button"><b>{kpi.high}</b><span>Initial H/E</span></button><button type="button"><b>{kpi.residualHigh}</b><span>Residual H/E</span></button><button type="button"><b>{kpi.improved}</b><span>Score Improved</span></button></div><div className="docfilters"><select value={kindFilter} onChange={e=>setKindFilter(e.target.value)}><option>Semua</option><option>Risk</option><option>Opportunity</option></select><select value={swotFilter} onChange={e=>setSwotFilter(e.target.value)}><option>Semua</option>{['Strength','Weakness','Opportunity','Threat'].map(x=><option key={x}>{x}</option>)}</select></div>
 {show&&<form className="panel" onSubmit={submit}><div className="formgrid"><label>Konteks Organisasi<select value={form.context_type} onChange={e=>setForm({...form,context_type:e.target.value})}><option>Internal</option><option>External</option></select></label><label>SWOT<select value={form.swot_type} onChange={e=>setForm({...form,swot_type:e.target.value})}>{['Strength','Weakness','Opportunity','Threat'].map(x=><option key={x}>{x}</option>)}</select></label></div>
 <label>Issue / Konteks Organisasi<textarea required value={form.issue} onChange={e=>setForm({...form,issue:e.target.value})}/></label>
 <label>Area Dampak / Kriteria Severity<select required value={form.impact_area} onChange={e=>setForm({...form,impact_area:e.target.value})}><option value="">Pilih area dampak</option>{IMPACT_AREAS.map(x=><option key={x}>{x}</option>)}</select></label>{form.impact_area&&<div className="notice"><span><b>Panduan {form.risk_or_opportunity==='Opportunity'?'Kriteria Peluang':'Severity Risiko'} — {form.impact_area}:</b> {guideFor(form.risk_or_opportunity,form.impact_area)?.map((x,i)=>`${i+1}: ${x}`).join(' · ')}</span></div>}<div className="formgrid"><label>Initial P (Likelihood 1–5)<select required value={form.initial_probability} onChange={e=>setForm({...form,initial_probability:e.target.value})}><option value="">Pilih</option>{[1,2,3,4,5].map(x=><option key={x} value={x}>{x} — {LIKELIHOOD[x]}</option>)}</select></label><label>Initial S (Impact 1–5)<select title={form.impact_area?guideFor(form.risk_or_opportunity,form.impact_area)?.map((x,i)=>`${i+1}: ${x}`).join(' | '):'Pilih area dampak terlebih dahulu'} required value={form.initial_severity} onChange={e=>setForm({...form,initial_severity:e.target.value})}><option value="">Pilih</option>{[1,2,3,4,5].map(x=><option key={x}>{x}</option>)}</select></label></div>
 <p><b>Initial Nilai:</b> {form.initial_probability&&form.initial_severity?Number(form.initial_probability)*Number(form.initial_severity):'-'} &nbsp; <b>Level:</b> {level(form.initial_probability,form.initial_severity)||'-'} {level(form.initial_probability,form.initial_severity)?`— ${LEVEL_NAME[level(form.initial_probability,form.initial_severity)]}`:''}</p>
 <div className="formgrid"><label>Klasifikasi<select value={form.risk_or_opportunity} onChange={e=>setForm({...form,risk_or_opportunity:e.target.value})}><option>Risk</option><option>Opportunity</option></select></label><label>Departemen / Business Unit<input value={form.department} onChange={e=>setForm({...form,department:e.target.value})}/></label></div>
 <label>Action Plan<textarea value={form.action_plan} onChange={e=>setForm({...form,action_plan:e.target.value})}/></label>
 <div className="formgrid"><label>Residual P<select value={form.residual_probability} onChange={e=>setForm({...form,residual_probability:e.target.value})}><option value="">-</option>{[1,2,3,4,5].map(x=><option key={x}>{x}</option>)}</select></label><label>Residual S<select value={form.residual_severity} onChange={e=>setForm({...form,residual_severity:e.target.value})}><option value="">-</option>{[1,2,3,4,5].map(x=><option key={x}>{x}</option>)}</select></label></div>
 <p><b>Residual Nilai:</b> {form.residual_probability&&form.residual_severity?Number(form.residual_probability)*Number(form.residual_severity):'-'} &nbsp; <b>Level:</b> {level(form.residual_probability,form.residual_severity)||'-'} {level(form.residual_probability,form.residual_severity)?`— ${LEVEL_NAME[level(form.residual_probability,form.residual_severity)]}`:''}</p>
 <label>Efektivitas Peluang<select value={form.opportunity_effectiveness} onChange={e=>setForm({...form,opportunity_effectiveness:e.target.value})}>{['Melebihi Harapan','Memenuhi Harapan','Dibawah Harapan','Dalam Progres'].map(x=><option key={x}>{x}</option>)}</select></label>
 <label>Further Action Plan<textarea value={form.further_action_plan} onChange={e=>setForm({...form,further_action_plan:e.target.value})}/></label>
 <label>PIC<select value={form.owner_id} onChange={e=>setForm({...form,owner_id:e.target.value})}><option value="">Unassigned</option>{users.map(u=><option key={u.id} value={u.id}>{u.full_name}{u.function_name?' · '+u.function_name:''}</option>)}</select></label>
 <div className="docactions"><button type="button" onClick={()=>setShow(false)}>Batal</button><button className="primary" disabled={saving}>{saving?'Menyimpan…':'Simpan Risk & Opportunity'}</button></div></form>}
 <div className="tablewrap"><table><thead><tr><th>Konteks</th><th>SWOT</th><th>Issue</th><th>Area Dampak</th><th>Initial P×S</th><th>R/P</th><th>Action Plan</th><th>Departemen</th><th>Residual P×S</th><th>Efektivitas</th><th>Further Action</th><th>PIC</th></tr></thead><tbody>{items.length?items.map(r=><tr key={r.id} onClick={()=>onOpen?.(r)}><td>{r.context_type||'-'}</td><td>{r.swot_type||'-'}</td><td>{r.risk_issue||r.title}</td><td>{r.impact_area||'-'}</td><td>{r.initial_score??'-'} {r.initial_score?('('+level(r.initial_probability,r.initial_severity)+')'):''}</td><td>{r.risk_or_opportunity||'-'}</td><td>{r.action_plan||'-'}</td><td>{r.department||'-'}</td><td>{r.residual_score??'-'} {r.residual_score?('('+level(r.residual_probability,r.residual_severity)+')'):''}</td><td>{r.opportunity_effectiveness||'-'}</td><td>{r.further_action_plan||'-'}</td><td>{r.owner||'Unassigned'}</td></tr>):<tr><td colSpan="12">Belum ada Risk & Opportunity.</td></tr>}</tbody></table></div></section>
}