'use client'
import {useMemo,useState} from 'react'

const level=(p,s)=>{const n=Number(p)*Number(s);if(!p||!s)return '';if(n===1)return 'N';if(n<=6)return 'L';if(n<=10)return 'M';if(n<=16)return 'H';return 'E'}
const empty={context_type:'Internal',swot_type:'Strength',issue:'',initial_probability:'',initial_severity:'',risk_or_opportunity:'Risk',action_plan:'',department:'',residual_probability:'',residual_severity:'',opportunity_effectiveness:'Dalam Progres',further_action_plan:'',owner_id:''}

export default function RiskOpportunityWorkspace({records=[],users=[],canWrite=false,onRefresh,onOpen}){
 const [form,setForm]=useState(empty),[show,setShow]=useState(false),[saving,setSaving]=useState(false),[notice,setNotice]=useState('')
 const items=useMemo(()=>records.filter(r=>r.module==='Risk & Opportunity'),[records])
 const submit=async e=>{e.preventDefault();if(!canWrite)return;setSaving(true);setNotice('');const payload={title:form.issue,module:'Risk & Opportunity',severity:level(form.initial_probability,form.initial_severity)||'Medium',description:form.action_plan,owner_id:form.owner_id||null,risk:{...form,initial_probability:Number(form.initial_probability),initial_severity:Number(form.initial_severity),residual_probability:form.residual_probability?Number(form.residual_probability):null,residual_severity:form.residual_severity?Number(form.residual_severity):null}};const r=await fetch('/api/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),d=await r.json().catch(()=>({}));if(!r.ok){setNotice(d.error||'Gagal menyimpan Risk & Opportunity');setSaving(false);return}setForm(empty);setShow(false);setSaving(false);setNotice('Risk & Opportunity berhasil ditambahkan.');if(onRefresh)await onRefresh()}
 return <section className="docworkspace"><div className="dochead"><div><h2>Risk & Opportunity — SWOT</h2><p>Format diselaraskan dengan register SWOT IMM: konteks organisasi, initial risk/opportunity, action plan, residual risk, efektivitas peluang, dan further action.</p></div>{canWrite&&<button className="primary" onClick={()=>setShow(!show)}>＋ Risk / Opportunity</button>}</div>
 {notice&&<div className="notice"><span>{notice}</span></div>}
 {show&&<form className="panel" onSubmit={submit}><div className="formgrid"><label>Konteks Organisasi<select value={form.context_type} onChange={e=>setForm({...form,context_type:e.target.value})}><option>Internal</option><option>External</option></select></label><label>SWOT<select value={form.swot_type} onChange={e=>setForm({...form,swot_type:e.target.value})}>{['Strength','Weakness','Opportunity','Threat'].map(x=><option key={x}>{x}</option>)}</select></label></div>
 <label>Issue / Konteks Organisasi<textarea required value={form.issue} onChange={e=>setForm({...form,issue:e.target.value})}/></label>
 <div className="formgrid"><label>Initial P (Likelihood 1–5)<select required value={form.initial_probability} onChange={e=>setForm({...form,initial_probability:e.target.value})}><option value="">Pilih</option>{[1,2,3,4,5].map(x=><option key={x}>{x}</option>)}</select></label><label>Initial S (Impact 1–5)<select required value={form.initial_severity} onChange={e=>setForm({...form,initial_severity:e.target.value})}><option value="">Pilih</option>{[1,2,3,4,5].map(x=><option key={x}>{x}</option>)}</select></label></div>
 <p><b>Initial Nilai:</b> {form.initial_probability&&form.initial_severity?Number(form.initial_probability)*Number(form.initial_severity):'-'} &nbsp; <b>Level:</b> {level(form.initial_probability,form.initial_severity)||'-'}</p>
 <div className="formgrid"><label>Klasifikasi<select value={form.risk_or_opportunity} onChange={e=>setForm({...form,risk_or_opportunity:e.target.value})}><option>Risk</option><option>Opportunity</option></select></label><label>Departemen / Business Unit<input value={form.department} onChange={e=>setForm({...form,department:e.target.value})}/></label></div>
 <label>Action Plan<textarea value={form.action_plan} onChange={e=>setForm({...form,action_plan:e.target.value})}/></label>
 <div className="formgrid"><label>Residual P<select value={form.residual_probability} onChange={e=>setForm({...form,residual_probability:e.target.value})}><option value="">-</option>{[1,2,3,4,5].map(x=><option key={x}>{x}</option>)}</select></label><label>Residual S<select value={form.residual_severity} onChange={e=>setForm({...form,residual_severity:e.target.value})}><option value="">-</option>{[1,2,3,4,5].map(x=><option key={x}>{x}</option>)}</select></label></div>
 <p><b>Residual Nilai:</b> {form.residual_probability&&form.residual_severity?Number(form.residual_probability)*Number(form.residual_severity):'-'} &nbsp; <b>Level:</b> {level(form.residual_probability,form.residual_severity)||'-'}</p>
 <label>Efektivitas Peluang<select value={form.opportunity_effectiveness} onChange={e=>setForm({...form,opportunity_effectiveness:e.target.value})}>{['Melebihi Harapan','Memenuhi Harapan','Dibawah Harapan','Dalam Progres'].map(x=><option key={x}>{x}</option>)}</select></label>
 <label>Further Action Plan<textarea value={form.further_action_plan} onChange={e=>setForm({...form,further_action_plan:e.target.value})}/></label>
 <label>PIC<select value={form.owner_id} onChange={e=>setForm({...form,owner_id:e.target.value})}><option value="">Unassigned</option>{users.map(u=><option key={u.id} value={u.id}>{u.full_name}{u.function_name?' · '+u.function_name:''}</option>)}</select></label>
 <div className="docactions"><button type="button" onClick={()=>setShow(false)}>Batal</button><button className="primary" disabled={saving}>{saving?'Menyimpan…':'Simpan Risk & Opportunity'}</button></div></form>}
 <div className="tablewrap"><table><thead><tr><th>Konteks</th><th>SWOT</th><th>Issue</th><th>Initial P×S</th><th>R/P</th><th>Action Plan</th><th>Departemen</th><th>Residual P×S</th><th>Efektivitas</th><th>Further Action</th><th>PIC</th></tr></thead><tbody>{items.length?items.map(r=><tr key={r.id} onClick={()=>onOpen?.(r)}><td>{r.context_type||'-'}</td><td>{r.swot_type||'-'}</td><td>{r.risk_issue||r.title}</td><td>{r.initial_score??'-'} {r.initial_score?('('+level(r.initial_probability,r.initial_severity)+')'):''}</td><td>{r.risk_or_opportunity||'-'}</td><td>{r.action_plan||'-'}</td><td>{r.department||'-'}</td><td>{r.residual_score??'-'} {r.residual_score?('('+level(r.residual_probability,r.residual_severity)+')'):''}</td><td>{r.opportunity_effectiveness||'-'}</td><td>{r.further_action_plan||'-'}</td><td>{r.owner||'Unassigned'}</td></tr>):<tr><td colSpan="11">Belum ada Risk & Opportunity.</td></tr>}</tbody></table></div></section>
}