'use client'
import {useEffect,useState} from 'react'
export default function EvidenceAccess(){
 const[me,setMe]=useState(null),[checked,setChecked]=useState(false),[records,setRecords]=useState([]),[evidence,setEvidence]=useState([]),[selected,setSelected]=useState(null),[permissions,setPermissions]=useState(null),[userQuery,setUserQuery]=useState(''),[accessFilter,setAccessFilter]=useState('Semua'),[error,setError]=useState(''),[saving,setSaving]=useState('')
 const canAdmin=['Super Admin','IMS Admin'].includes(me?.profile?.app_role)
 useEffect(()=>{fetch('/api/me').then(r=>r.ok?r.json():null).then(d=>{setMe(d);setChecked(true)})},[])
 useEffect(()=>{if(!checked||!canAdmin)return;fetch('/api/records').then(r=>r.ok?r.json():[]).then(x=>setRecords(x.filter(r=>r.module==='Document & Record Control')))},[checked,canAdmin])
 const loadEvidence=async record=>{if(!canAdmin)return;setSelected(record);setPermissions(null);setError('');const r=await fetch('/api/evidence?record_id='+record.id);setEvidence(r.ok?await r.json():[])}
 const manage=async item=>{if(!canAdmin)return;setError('');const r=await fetch(`/api/evidence/${item.id}/permissions`);const d=await r.json().catch(()=>({}));if(!r.ok)return setError(d.error||'Unable to load permissions');setPermissions(d)}
 const toggle=async(user,value)=>{if(!canAdmin||!permissions||user.permission_source==='admin-role')return;setSaving(user.id);setError('');const r=await fetch(`/api/evidence/${permissions.evidence.id}/authorize`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({user_id:user.id,can_download:value})});const d=await r.json().catch(()=>({}));if(!r.ok)setError(d.error||'Unable to update access');else setPermissions(p=>({...p,users:p.users.map(u=>u.id===user.id?{...u,explicit_can_download:d.can_download,effective_can_download:d.can_download,permission_source:d.can_download?'explicit':'none'}:u)}));setSaving('')}
 if(!checked)return <main className="adminpage"><p>Memeriksa hak akses…</p></main>
 if(!canAdmin)return <main className="adminpage"><div className="panelhead"><a href="/">← Control Room</a></div><h1>Controlled Download Access</h1><div className="notice"><span>Pengaturan izin download dokumen terkontrol hanya dapat dikelola oleh Super Admin atau IMS Admin.</span></div></main>
 return <main className="adminpage"><header><div><p className="eyebrow">DOCUMENT GOVERNANCE</p><h1>Controlled Download Access</h1><p>Grant or revoke explicit download permission for controlled document attachments. Super Admin and IMS Admin remain authorized by role.</p></div><a href="/">← Control Room</a></header><section className="panel"><div className="panelhead"><h2>Controlled Documents</h2><span className="count">{records.length} records</span></div>{records.length?records.map(r=><button className="notif" key={r.id} onClick={()=>loadEvidence(r)}><b>{r.document_number||r.record_no} · Rev {r.revision||'-'}</b><span>{r.title}</span><small>{r.document_status||r.status}</small></button>):<p className="empty">No controlled documents.</p>}</section>{selected&&<section className="panel"><div className="panelhead"><h2>Attachments · {selected.document_number||selected.record_no}</h2><span className="count">{evidence.length}</span></div>{evidence.length?evidence.map(e=><div className="approverdecision" key={e.id}><div><b>{e.file_name}</b><small>{e.mime_type||'File'} · {e.uploaded_by||'-'}</small></div><button onClick={()=>manage(e)}>Manage Access</button></div>):<p className="empty">No attachment registered for this document.</p>}</section>}{permissions&&<section className="panel"><div className="panelhead"><div><p className="eyebrow">ACCESS MATRIX</p><h2>{permissions.evidence.file_name}</h2></div><span className="count">Admin controlled</span></div><div className="docfilters"><input placeholder="Cari user, email, role..." value={userQuery} onChange={e=>setUserQuery(e.target.value)}/><select value={accessFilter} onChange={e=>setAccessFilter(e.target.value)}><option>Semua</option><option>Authorized</option><option>Restricted</option></select><button onClick={()=>{setUserQuery('');setAccessFilter('Semua')}}>Reset</button></div><table><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Access Source</th><th>Download</th></tr></thead><tbody>{permissions.users.filter(u=>(accessFilter==='Semua'||(accessFilter==='Authorized'?u.effective_can_download:!u.effective_can_download))&&(!userQuery||`${u.full_name} ${u.email} ${u.app_role}`.toLowerCase().includes(userQuery.toLowerCase()))).map(u=>{const roleBased=u.permission_source==='admin-role';return <tr key={u.id}><td><b>{u.full_name}</b><br/>{u.email}</td><td>{u.app_role}</td><td>{u.active?'Active':'Disabled'}</td><td>{roleBased?'Role-based':u.permission_source==='explicit'?'Explicit permission':'No permission'}</td><td>{roleBased?<span className="pill">Always authorized</span>:<button disabled={saving===u.id||!u.active} onClick={()=>toggle(u,!u.effective_can_download)}>{saving===u.id?'Saving…':u.effective_can_download?'Revoke':'Grant'}</button>}</td></tr>})}</tbody></table></section>}{error&&<p className="error">{error}</p>}</main>
}
