'use client'
import {useEffect,useMemo,useState} from 'react'
import DocumentWorkspace from './components/DocumentWorkspace'
import ModuleWorkspace from './components/ModuleWorkspace'
import EvidencePanel from './components/EvidencePanel'
import DistributionPanel from './components/DistributionPanel'
import NotificationCenter from './components/NotificationCenter'
import ManagementDashboard from './components/ManagementDashboard'
const menu=['Overview','Business Process','Standar dan Persyaratan','Organization & Context','Leadership & Policy','Risk & Opportunity','Legal & Compliance','Objectives & KPI','Document & Record Control','Competency & Awareness','Communication & Consultation','Operational Control','Quality Management','Environmental Management','OH&S Management','SMK3','SMKP Minerba','Laboratory Management','Contractor & Supplier','Incident, NCR & CAPA','Audit & Assessment','Inspection & Monitoring','Emergency Preparedness','Management Review','Performance & Analytics','Improvement & Lessons Learned']
const WRITE=['Super Admin','IMS Admin','Auditor','Function Owner']
const emptyForm=module=>({title:'',module,severity:'Medium',due_date:'',description:'',document_number:'',document_type:'',revision:'00',classification:'Internal',retention:'',effective_date:''})
export default function Home(){
 const[records,setRecords]=useState([]),[notifications,setNotifications]=useState([]),[me,setMe]=useState(null),[active,setActive]=useState('Overview'),[selected,setSelected]=useState(null),[approval,setApproval]=useState(null),[evidence,setEvidence]=useState([]),[history,setHistory]=useState([]),[auditTrail,setAuditTrail]=useState({audit:[],workflow:[]}),[detailTab,setDetailTab]=useState('Informasi Umum'),[comment,setComment]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false),[showForm,setShowForm]=useState(false),[showRevision,setShowRevision]=useState(false),[revision,setRevision]=useState({revision:'',title:''}),[form,setForm]=useState(emptyForm('Document & Record Control'))
 const load=()=>fetch('/api/records').then(r=>r.ok?r.json():[]).then(setRecords);const loadEvidence=async id=>{const r=await fetch('/api/evidence?record_id='+id);if(r.ok)setEvidence(await r.json())}
 useEffect(()=>{load();fetch('/api/notifications').then(r=>r.ok?r.json():[]).then(setNotifications);fetch('/api/me').then(r=>r.ok?r.json():null).then(setMe)},[])
 const stats=useMemo(()=>({documents:records.filter(r=>r.module==='Document & Record Control').length,review:records.filter(r=>r.status==='In Review').length,open:records.filter(r=>r.status==='Open').length,critical:records.filter(r=>['Critical','Major'].includes(r.severity)&&!['Approved','Closed'].includes(r.status)).length}),[records])
 const openRecord=async r=>{setSelected(r);setDetailTab('Informasi Umum');setError('');setComment('');setApproval(null);setEvidence([]);setHistory([]);setAuditTrail({audit:[],workflow:[]});const[a,e,h,t]=await Promise.all([fetch('/api/approvals?record_id='+r.id),fetch('/api/evidence?record_id='+r.id),fetch('/api/documents/history?record_id='+r.id),fetch('/api/records/'+r.id+'/audit')]);if(a.ok)setApproval(await a.json());if(e.ok)setEvidence(await e.json());if(h.ok)setHistory(await h.json());if(t.ok)setAuditTrail(await t.json())}
 const createRecord=async e=>{e.preventDefault();setSaving(true);setError('');const payload={title:form.title,module:form.module,severity:form.severity,due_date:form.due_date||null,description:form.description};if(form.module==='Document & Record Control')payload.document={document_number:form.document_number,document_type:form.document_type,revision:form.revision||'00',classification:form.classification||'Internal',retention:form.retention||null,effective_date:form.effective_date||null};const r=await fetch('/api/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),d=await r.json().catch(()=>({}));if(!r.ok){setError(d.error||'Gagal membuat record');setSaving(false);return}const wr=await fetch('/api/approvals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({record_id:d.id})}),wd=await wr.json().catch(()=>({}));setShowForm(false);await load();await openRecord({...d,module:form.module,title:form.title,due_date:form.due_date||null});if(!wr.ok)setError(`Record berhasil dibuat, tetapi workflow approval belum dimulai: ${wd.error||'workflow belum tersedia'}`);setSaving(false)}
 const decide=async decision=>{if(!comment.trim())return setError('Keterangan / komentar wajib diisi');setSaving(true);const r=await fetch('/api/approvals',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({record_id:selected.id,decision,comment})}),d=await r.json().catch(()=>({}));if(!r.ok)setError(d.error||'Approval gagal');else{await load();await openRecord(selected)}setSaving(false)}
 const createRevision=async e=>{e.preventDefault();setSaving(true);const r=await fetch('/api/documents/revisions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source_record_id:selected.id,revision:revision.revision,title:revision.title})}),d=await r.json().catch(()=>({}));if(!r.ok){setError(d.error||'Gagal membuat revisi');setSaving(false);return}await fetch('/api/approvals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({record_id:d.record.id})});setShowRevision(false);await load();await openRecord(d.record);setSaving(false)}
 const pending=approval?.approvals?.find(a=>a.decision==='Pending'),role=me?.profile?.app_role,userId=approval?.current_user_id||me?.profile?.id,already=pending?.decisions?.some(d=>String(d.approver_id)===String(userId)),canApprove=!!pending&&!already&&(['Super Admin','IMS Admin'].includes(role)||role===pending.required_role),isDoc=selected?.module==='Document & Record Control',tabs=isDoc?['Informasi Umum','Revisi','File & Lampiran','Approval','Distribusi','Riwayat']:['Informasi Umum','File & Lampiran','Approval','Riwayat']
 const audit=[...(auditTrail.audit||[]),...(auditTrail.workflow||[]).map(w=>({...w,action:`${w.from_status||'-'} → ${w.to_status}`,detail:{note:w.note}}))].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))
 const openNew=module=>{setForm(emptyForm(module));setError('');setShowForm(true)}
 return <div className="shell"><aside><div className="brand"><div className="mark">IMM</div><div><strong>Integrated Management System</strong><small>PT Indominco Mandiri</small></div></div><nav>{menu.map(x=><button key={x} className={active===x?'active':''} onClick={()=>setActive(x)}>{x}</button>)}</nav><a className="admin" href="/admin">⚙ Administration & Access</a></aside><main><header><div><p className="eyebrow">PT INDOMINCO MANDIRI</p><h1>{active==='Overview'?'Integrated Management System':active}</h1><p>Satu Sistem, Satu Kepatuhan, Untuk Keberlanjutan</p></div><NotificationCenter notifications={notifications} setNotifications={setNotifications} records={records} onOpen={openRecord}/></header>
 {active==='Overview'&&<><section className="heroims"><div><h2>Selamat Datang,<br/>di Integrated Management System<br/>PT Indominco Mandiri</h2><p>“Compliance Today, Sustainable Tomorrow”</p></div></section><section className="metrics"><div><b>{stats.documents}</b><span>Jumlah Dokumen</span></div><div><b>{stats.review}</b><span>Dalam Approval</span></div><div><b>{stats.open}</b><span>Open Records</span></div><div><b>{stats.critical}</b><span>Major / Critical</span></div></section><ManagementDashboard records={records} onOpen={openRecord} onNavigate={setActive}/></>}
 {active==='Document & Record Control'&&<DocumentWorkspace records={records} onOpen={openRecord} onNew={()=>openNew('Document & Record Control')} onRefresh={load}/>} 
 {active!=='Overview'&&active!=='Document & Record Control'&&<ModuleWorkspace module={active} records={records} onOpen={openRecord} onNew={()=>openNew(active)}/>} 
 {showForm&&<div className="modalback"><form className="modal" onSubmit={createRecord}><div className="panelhead"><div><p className="eyebrow">NEW IMS RECORD</p><h2>{form.module}</h2></div><button type="button" className="close" onClick={()=>setShowForm(false)}>×</button></div><label>Title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><div className="formgrid"><label>Severity<select value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})}>{['Low','Medium','Major','Critical'].map(x=><option key={x}>{x}</option>)}</select></label><label>Due Date<input type="date" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})}/></label></div>{form.module==='Document & Record Control'&&<><div className="formgrid"><label>Document Number<input required value={form.document_number} onChange={e=>setForm({...form,document_number:e.target.value})}/></label><label>Document Type<input required value={form.document_type} onChange={e=>setForm({...form,document_type:e.target.value})}/></label></div><div className="formgrid"><label>Revision<input value={form.revision} onChange={e=>setForm({...form,revision:e.target.value})}/></label><label>Classification<select value={form.classification} onChange={e=>setForm({...form,classification:e.target.value})}><option>Internal</option><option>Confidential</option><option>Restricted</option><option>Public</option></select></label></div><div className="formgrid"><label>Retention<input placeholder="contoh: 5 tahun" value={form.retention} onChange={e=>setForm({...form,retention:e.target.value})}/></label><label>Planned Effective Date<input type="date" value={form.effective_date} onChange={e=>setForm({...form,effective_date:e.target.value})}/></label></div></>}<label>Uraian / Keterangan<textarea rows="4" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}></textarea></label>{error&&<p className="error">{error}</p>}<button className="primary" disabled={saving}>{saving?'Menyimpan…':'Create & Start Workflow'}</button></form></div>}
 {selected&&<div className="modalback"><div className="modal documentdetail"><div className="panelhead"><div><p className="eyebrow">{isDoc?'DETAIL DOKUMEN':'DETAIL RECORD'}</p><h2>{isDoc?(approval?.record?.document_number||selected.record_no):selected.record_no} · {selected.title}</h2></div><button className="close" onClick={()=>setSelected(null)}>×</button></div><div className="detailtabs">{tabs.map(t=><button key={t} className={detailTab===t?'active':''} onClick={()=>setDetailTab(t)}>{t}</button>)}</div>
 {detailTab==='Informasi Umum'&&(isDoc?<div className="recordmeta"><span>Document No.<b>{approval?.record?.document_number||selected.document_number||'-'}</b></span><span>Revision<b>{approval?.record?.revision||selected.revision||'-'}</b></span><span>Status<b>{approval?.record?.document_status||selected.document_status||selected.status}</b></span><span>Classification<b>{approval?.record?.classification||selected.classification||'-'}</b></span><span>Effective Date<b>{approval?.record?.effective_date||selected.effective_date||'-'}</b></span><span>Retention<b>{approval?.record?.retention||selected.retention||'-'}</b></span></div>:<div className="recordmeta"><span>Record No.<b>{selected.record_no}</b></span><span>Module<b>{selected.module}</b></span><span>Status<b>{selected.status}</b></span><span>Severity<b>{selected.severity||'-'}</b></span><span>Due Date<b>{selected.due_date||'-'}</b></span><span>PIC<b>{selected.owner||'Unassigned'}</b></span></div>)}
 {detailTab==='Revisi'&&isDoc&&<div className="approvalflow"><div className="panelhead"><h3>Riwayat Revisi</h3>{approval?.record?.document_status==='Effective'&&<button onClick={()=>{setRevision({revision:'',title:selected.title});setShowRevision(true)}}>+ Ajukan Revisi</button>}</div>{history.length?history.map(h=><div className="approvalstep" key={h.id}><span>{h.revision}</span><div><b>{h.document_number}</b><small>{h.document_status} · {h.effective_date||'Not effective'}</small></div></div>):<p className="empty">Belum ada riwayat revisi.</p>}</div>}
 {detailTab==='File & Lampiran'&&<EvidencePanel record={selected} evidence={evidence} canUpload={WRITE.includes(role)} onRefresh={()=>loadEvidence(selected.id)}/>} 
 {detailTab==='Approval'&&<div className="approvalflow">{approval?.approvals?.length?approval.approvals.map(a=><div className="approvalstep" key={a.id}><span>{a.level_no}</span><div><b>{a.level_name}</b><small>{a.required_role} · {a.approved_count}/{a.required_approvals} Approved · {a.decision}</small><small>{a.description||'Tidak ada instruksi tambahan.'}</small>{a.decisions?.map(d=><p key={d.id}>{d.approver}: {d.comment}</p>)}</div></div>):<p className="empty">Belum ada workflow approval aktif untuk record ini.</p>}{canApprove&&<div><label>Keterangan / Komentar<textarea rows="3" value={comment} onChange={e=>setComment(e.target.value)}></textarea></label><div className="decision"><button onClick={()=>decide('Rejected')}>Tolak</button><button className="primary" onClick={()=>decide('Approved')}>Setujui</button></div></div>}{already&&<div className="notice"><span>Keputusan pada level ini sudah diberikan.</span></div>}</div>}
 {detailTab==='Distribusi'&&isDoc&&<DistributionPanel record={selected} role={role}/>} 
 {detailTab==='Riwayat'&&<div className="approvalflow"><h3>Audit Trail</h3>{audit.map((x,i)=><div className="approvalstep" key={x.id||i}><span>•</span><div><b>{x.action}</b><small>{x.actor||'System'}{x.app_role?' · '+x.app_role:''} · {new Date(x.created_at).toLocaleString('id-ID')}</small>{x.detail?.note&&<p>{x.detail.note}</p>}</div></div>)}{!audit.length&&<p className="empty">Belum ada aktivitas tercatat.</p>}</div>}{error&&<p className="error">{error}</p>}</div></div>}
 {showRevision&&<div className="modalback"><form className="modal" onSubmit={createRevision}><div className="panelhead"><h2>Ajukan Revisi Dokumen</h2><button type="button" className="close" onClick={()=>setShowRevision(false)}>×</button></div><label>Revisi Baru<input required value={revision.revision} onChange={e=>setRevision({...revision,revision:e.target.value})}/></label><label>Judul Dokumen<input required value={revision.title} onChange={e=>setRevision({...revision,title:e.target.value})}/></label>{error&&<p className="error">{error}</p>}<button className="primary" disabled={saving}>Buat Revisi & Mulai Approval</button></form></div>}
 </main></div>
}
