'use client'
import {useEffect,useState} from 'react'
const standards=['ISO 9001','ISO 14001','ISO 45001','SMK3','SMKP Minerba','ISO/IEC 17025']
const menu=['Overview','Business Process','Standar dan Persyaratan','Risk & Opportunity','Legal & Compliance','Objectives & KPI','Document & Record Control','Competency','Operational Control','Audit & Assessment','NCR & CAPA','Emergency Preparedness','Management Review','Improvement']
export default function Home(){
 const [records,setRecords]=useState([]),[health,setHealth]=useState(null),[active,setActive]=useState('Overview')
 useEffect(()=>{fetch('/api/records').then(r=>r.ok?r.json():[]).then(setRecords).catch(()=>{});fetch('/api/health').then(r=>r.json()).then(setHealth).catch(()=>{})},[])
 return <div className="shell"><aside><div className="brand"><div className="mark">IMM</div><div><strong>Integrated Management System</strong><small>Control Room</small></div></div><nav>{menu.map(x=><button className={active===x?'active':''} onClick={()=>setActive(x)} key={x}>{x}</button>)}</nav><a className="admin" href="/admin">Administration & Access</a></aside><main><header><div><p className="eyebrow">PT INDOMINCO MANDIRI</p><h1>{active}</h1><p>Integrated assurance, compliance and continual improvement.</p></div><div className="health">● {health?.ok?'Production connected':'Configuration check'}</div></header><section className="standards">{standards.map((s,i)=><article key={s}><span>0{i+1}</span><b>{s}</b><small>Integrated requirement</small></article>)}</section><section className="grid"><article className="panel wide"><div className="panelhead"><div><p className="eyebrow">ASSURANCE</p><h2>IMS Executive Control</h2></div><button>New Record</button></div><div className="metrics"><div><b>{records.length}</b><span>Active records</span></div><div><b>{records.filter(x=>x.status==='In Review').length}</b><span>In review</span></div><div><b>{records.filter(x=>x.severity==='Critical').length}</b><span>Critical</span></div><div><b>6</b><span>Frameworks</span></div></div></article><article className="panel"><p className="eyebrow">GOVERNANCE</p><h2>Control Architecture</h2><p>Risk-based controls, multi-level approval, evidence, audit trail and role-based access are managed as one governance chain.</p><a href="/admin">Open Administration →</a></article></section><section className="panel"><div className="panelhead"><div><p className="eyebrow">LIVE REGISTER</p><h2>Priority Work Queue</h2></div></div>{records.length?<table><thead><tr><th>Record</th><th>Module</th><th>Owner</th><th>Status</th><th>Severity</th></tr></thead><tbody>{records.slice(0,8).map(r=><tr key={r.id}><td><b>{r.record_no}</b><br/>{r.title}</td><td>{r.module}</td><td>{r.owner}</td><td><span className="pill">{r.status}</span></td><td>{r.severity}</td></tr>)}</tbody></table>:<div className="empty"><b>Production register ready</b><p>Records will appear here after the Neon connection is configured on deployment.</p></div>}</section></main></div>
}
