import { db } from '@/lib/db'
import { requireAccess } from '@/lib/auth/access'
const READ=['Super Admin','IMS Admin','Auditor','Function Owner','Viewer'],WRITE=['Super Admin','IMS Admin','Auditor','Function Owner'],STATUSES=['Open','In Review','Approved','Closed']
export async function GET(){const access=await requireAccess(READ);if(!access.ok)return access.response;const sql=db();return Response.json(await sql`select r.id,r.record_no,r.title,r.module,r.status,r.severity,r.due_date,r.description,r.owner_id,coalesce(u.full_name,'Unassigned') owner,u.function_name owner_function,d.document_number,d.document_type,d.revision,d.effective_date,d.retention,d.classification,d.document_status from ims_records r left join app_users u on u.id=r.owner_id left join controlled_documents d on d.record_id=r.id order by r.created_at desc limit 200`)}
export async function POST(req){
 const access=await requireAccess(WRITE);if(!access.ok)return access.response;const body=await req.json();if(!body.title||!body.module)return Response.json({error:'title and module are required'},{status:400});const severities=['Low','Medium','Major','Critical'];if(body.severity&&!severities.includes(body.severity))return Response.json({error:'invalid severity'},{status:400})
 const isDoc=body.module==='Document & Record Control',d=body.document||{};if(isDoc&&(!String(d.document_number||'').trim()||!String(d.document_type||'').trim()))return Response.json({error:'Document number and document type are required'},{status:400})
 const sql=db();let ownerId=null;if(body.owner_id){const owner=(await sql`select id,active from app_users where id=${body.owner_id} limit 1`)[0];if(!owner||!owner.active)return Response.json({error:'owner must be an active IMS user'},{status:400});ownerId=owner.id}if(isDoc){const duplicate=await sql`select id from controlled_documents where document_number=${String(d.document_number).trim()} and revision=${String(d.revision||'00').trim()} limit 1`;if(duplicate.length)return Response.json({error:'This document number and revision already exists'},{status:409})}
 const no=`IMS-${Date.now().toString(36).toUpperCase()}-${crypto.randomUUID().slice(0,6).toUpperCase()}`;let record
 try{record=(await sql`insert into ims_records(record_no,title,module,status,severity,due_date,description,owner_id,created_by) values(${no},${body.title},${body.module},'Open',${body.severity||'Medium'},${body.due_date||null},${body.description||''},${ownerId},${access.profile.id}) returning id,record_no,title,module,status,severity,due_date,description,owner_id`)[0];if(isDoc)await sql`insert into controlled_documents(record_id,document_number,document_type,revision,effective_date,retention,classification,document_status) values(${record.id},${String(d.document_number).trim()},${String(d.document_type).trim()},${String(d.revision||'00').trim()},${d.effective_date||null},${d.retention||null},${d.classification||'Internal'},'Draft')`}
 catch(e){if(record?.id)await sql`delete from ims_records where id=${record.id}`;if(String(e?.message||'').includes('uq_controlled_documents_number_revision'))return Response.json({error:'This document number and revision already exists'},{status:409});throw e}
 await sql`insert into workflow_history(record_id,from_status,to_status,note,actor_id) values(${record.id},null,'Open','Record created',${access.profile.id})`;await sql`insert into audit_log(actor_id,action,entity_type,entity_id,detail) values(${access.profile.id},'CREATE','ims_record',${String(record.id)},${JSON.stringify({record_no:no,module:body.module,owner_id:ownerId})}::jsonb)`;if(ownerId&&String(ownerId)!==String(access.profile.id))await sql`insert into notifications(user_id,record_id,type,message) values(${ownerId},${record.id},'OWNER_ASSIGNED',${`Anda ditetapkan sebagai PIC ${no} · ${body.title}`})`;return Response.json(record,{status:201})
}
export async function PATCH(req){const access=await requireAccess(WRITE);if(!access.ok)return access.response;const b=await req.json();if(!b.id)return Response.json({error:'id is required'},{status:400});const sql=db(),current=(await sql`select id,status,record_no,title,owner_id from ims_records where id=${b.id} limit 1`)[0];if(!current)return Response.json({error:'record not found'},{status:404});if(b.owner_id!==undefined){let ownerId=null;if(b.owner_id){const owner=(await sql`select id,active from app_users where id=${b.owner_id} limit 1`)[0];if(!owner||!owner.active)return Response.json({error:'owner must be an active IMS user'},{status:400});ownerId=owner.id}const r=(await sql`update ims_records set owner_id=${ownerId},updated_at=now() where id=${b.id} returning id,record_no,status,owner_id`)[0];await sql`insert into audit_log(actor_id,action,entity_type,entity_id,detail) values(${access.profile.id},'ASSIGN_OWNER','ims_record',${String(b.id)},${JSON.stringify({record_no:current.record_no,from_owner_id:current.owner_id,to_owner_id:ownerId})}::jsonb)`;if(ownerId&&String(ownerId)!==String(current.owner_id)&&String(ownerId)!==String(access.profile.id))await sql`insert into notifications(user_id,record_id,type,message) values(${ownerId},${b.id},'OWNER_ASSIGNED',${`Anda ditetapkan sebagai PIC ${current.record_no} · ${current.title}`})`;return Response.json(r)}if(!STATUSES.includes(b.status))return Response.json({error:'valid status is required'},{status:400});if(['Approved','Closed'].includes(b.status)&&!['Super Admin','IMS Admin','Auditor'].includes(access.profile.app_role))return Response.json({error:'Approval or closure requires assurance authority'},{status:403});const r=await sql`update ims_records set status=${b.status},updated_at=now() where id=${b.id} returning id,record_no,status,owner_id`;await sql`insert into workflow_history(record_id,from_status,to_status,note,actor_id) values(${b.id},${current.status},${b.status},${b.note||'Status updated'},${access.profile.id})`;await sql`insert into audit_log(actor_id,action,entity_type,entity_id,detail) values(${access.profile.id},'STATUS_CHANGE','ims_record',${String(b.id)},${JSON.stringify({record_no:current.record_no,from:current.status,to:b.status,note:b.note||''})}::jsonb)`;return Response.json(r[0])}
